spring:
  application:
    name: nfcdetector
server:
  port: 8083

camunda.bpm.client:
  base-url: http://camunda:8080/engine-rest
  worker-id: nfc-detector-worker
  basic-auth:
    username: admin
    password: admin
    subscriptions:
      nfc-detect: # topic name of the External Service Task
        variable-names: []

mqtt:
  broker: tcp://192.168.0.10:1883
  user: txt
  pwd: xtx
  topic: f/i/nfc

camunda:
  storage:
    activity: activity_storage_nfc
  production:
    activity: activity_production_nfc